name: Insured Assurance CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Upload WAR artifact
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: insuredassurance1-war
          path: target/*.war

      # Step 5: Trigger Jenkins job via SSH using secrets
      - name: Trigger Jenkins Job via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Connected to server successfully!"

            # Trigger Jenkins job securely using secrets
            curl -u admin:${{ secrets.JENKINS_TOKEN }} \
            "http://localhost:8080/job/InsuredAssurance/build?token=mytoken"

            echo "Jenkins job triggered successfully!"
